# Generated by Django 4.1.2 on 2022-10-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DueDate', models.DateField()),
                ('Category', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField()),
            ],
        ),
    ]
